version: 2

sources:
  - name: dvdrental
    schema: public
    tables:
      - name: actor
      - name: film
      - name: film_actor
      - name: film_category
      - name: category
      - name: inventory
      - name: rental
      - name: payment
      - name: store
      - name: address
      - name: city
      - name: country
      - name: customer
      - name: language
      - name: staff